create database customer_behavior;
use customer_behavior;

select * from customers
limit 10;

-- what is the total rebenue generated by male vs female customers?

select gender,sum(purchased_amount) as revenue from customers
group by gender;

-- which customer used a discount but still spent more than the average purchase amount?

select customer_id,purchased_amount from customers
where discount_applied = 'Yes' and purchased_amount >= (select avg(purchased_amount) from customers);

-- which are the top  5 products with the highest average review rating?

select item_purchased, round(avg(review_rating),2) as avg_review_rating
from customers 
group by item_purchased
order by avg_review_rating desc
limit 5;

-- compare the average purchase amounts between standard and express shipping.

select shipping_type,round(avg(purchased_amount),2) from customers
where shipping_type in ('standard','express')
group by shipping_type;


-- Do subscribed customers spend more ? compare avergae spend and total revenue between subscribers and non-subscriber

select subscription_status,count(customer_id) as tota_customer,
avg(purchased_amount) as average_spend,
sum(purchased_amount) as total_revenue 
from customers
group by subscription_status
order by total_revenue,average_spend desc;



-- Which 5 products have the highest percentage of purchase with discounts applied?

select item_purchased,round(sum(case when discount_applied = 'Yes'then 1 else 0 end)/count(*)*100,2)
as discount_rate_percentage from customers
group by item_purchased
order by discount_rate_percentage desc
limit 5;

-- Segment customers into new, returing, and loyal based on their total 
-- number of previous purchases, and show the count of each segment

-- with customer_type as (
-- select customer_id,previous_purchases,
-- case 
-- when previous_purchases = 1 then 'New'
-- when previous_purchases between 2 and 10 then 'Returining'
-- else 'Loyal'
-- end as customer_segments
-- from customers
-- )

-- select customer_segments,count(*) as number_of_customers from customer_type
-- group by customer_segments;

select 
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returining'
else 'Loyal'
end as customer_segment , count(*) as number_of_customers from customers
group by customer_segment;


-- What are the top 3 most purchases products within each categorgory 

with item_count as (
select category,item_purchased,sum(purchased_amount) as total_amount ,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders from item_count
where item_rank <= 3;


-- Are customers who  are repeat buyers (more than 5 previous purchases) also likely to subscribtion

select * from customers limit 5;

select subscription_status,count(customer_id) as repeat_buyers from
customers 
where previous_purchases > 5
group by subscription_status;

-- What is the revenue contribute of each age group

select age_group,sum(purchased_amount) as total_revenue from customers 
group by age_group
order by total_revenue desc;